language: java
sudo: false
addons:
  apt:
    packages:
    - python3-openssl
    - google-cloud-sdk
jdk:
  - openjdk7
  - oraclejdk7

before_deploy:
  - mvn appengine:update

deploy:
  provider: gae
  keyfile: mixxy-secret.json
  project: mixxy-1249
  config: src/main/webapp/WEB-INF/appengine-web.xml
  on:
    jdk: oraclejdk7

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - openssl aes-256-cbc -K $encrypted_acb534f64c3b_key -iv $encrypted_acb534f64c3b_iv
    -in mixxy-secret.json.enc -out mixxy-secret.json -d
  - gcloud auth activate-service-account "$SERVICE_EMAIL" --key-file mixxy-secret.json --project "$PROJECT_ID"
